# 1. 아래 list를 numpy array로 바꿔보세요.

In [1]:
list_ = [4,5]

In [2]:
import numpy as np
#답안을 입력해주세요.
np.array(list_)

array([4, 5])

# 2. 1 ~ 9 사이의 정수를 하나씩 활용해서, 3 by 3 행렬을 출력하는 코드를 완성해보세요.

In [3]:
#2번 문제의 답변을 입력해주세요.
arr = np.arange(1,10)
np.random.shuffle(arr)
arr.reshape(3,3)

array([[1, 4, 7],
       [9, 2, 5],
       [3, 6, 8]])

# 3. 2에서 출력한 행렬의 차원을 알아내는 코드를 작성해보세요.

In [4]:
#3번 문제의 답변을 입력해주세요.
arr.reshape(3,3).shape

(3, 3)

# 4. 아래 정의된 arr1 로 numpy array를 만들고, arr1을 shape가 3 by 4 matrix로 만들어보세요.

In [5]:
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr1 = arr1.reshape(3,4)
arr1
#4번 문제의 답변을 입력해주세요.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# 4-1. 열기준으로 최대값의 인덱스를 구하는 코드를 완성해보세요.

In [6]:
np.max(arr1, 1)

array([ 4,  8, 12])

# 5. m, n 요소끼리의 곱셈, 나눗셈을 각각 구하는 코드를 짜보세요.

In [7]:
m = np.array([1,3,5])

n = np.array([4,5,6])

#5번 문제의 답변을 입력해주세요.
print(m*n)
print(m/n)

[ 4 15 30]
[0.25       0.6        0.83333333]


# 6. 4번 반복을 통해 출력되는 결과가 아래와 같도록 코드를 완성해보세요.

['a' 'a' 'a' 'a' 'b' 'b' 'b' 'b' 'c' 'c' 'c' 'c']

In [8]:
#6번 문제의 답변을 입력해주세요.

arr = np.array(['a','b','c'])#.reshape(3,1)
np.repeat(arr, 4)

array(['a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'c', 'c', 'c', 'c'],
      dtype='<U1')

# 7. 0 ~ 12까지의 제곱수가 12 by 1로 출력되도록 코드를 짜보세요.

In [9]:
#7번 문제의 답변을 입력해주세요.
arr = np.arange(1,13)
arr_sqrd = arr*arr
arr_sqrd

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

# 8. 7의 결과에서 왼쪽에서 3번째 숫자부터, 오른쪽 방향으로 두 개씩 데이터가 출력되도록 코드를 짜보세요.

In [10]:
#8번 문제의 답변을 입력해주세요.
for i in range(3,len(arr_sqrd),2):
    print(arr_sqrd[i:i+2])

[16 25]
[36 49]
[64 81]
[100 121]
[144]


# 9. 1로만 이뤄진 3 by 2 행렬 j을 두번째 행의 2열까지 3으로 만드는 코드를 완성해보세요.

In [11]:
j = np.array([[1,1,1],
            [1,1,1]])
#9번 문제의 답변을 입력해주세요.
j[:2,:2] = j[:2,:2]*3
j

array([[3, 3, 1],
       [3, 3, 1]])

# 0 ~ 35까지의 정수를 6 by 6으로 출력하는 코드를 바탕으로, 다음 문제를 풀어보세요.

10-1. 4행의 2 ~ 4열의 요소를 출력해보세요.

10-2. 행은 2행까지, 열은 5열까지 출력하는 코드를 짜보세요.

10-3. 5번째 행에서, 왼쪽에서 두 번째 숫자부터 두 개씩 건너띄도록 데이터를 출력해보세요.



In [12]:
#10-1.
arr = np.arange(36).reshape(6,6)
print(arr)
arr[3,2:5]

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([20, 21, 22])

In [13]:
# 10-2.
arr[:2,:5]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [14]:
# 10-3.
arr[4,1::2]

array([25, 27, 29])